# Generated by Django 5.0.2 on 2024-04-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_generator', '0002_rename_video_link_articlepost_youtube_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='youtube_title',
            new_name='video_title',
        ),
    ]
